language: python
python:
  - 3.4

install:
  - rvm use 2.1.1 --install --binary --fuzzy
  - npm install -g mapshaper
  - pip install html5validator pandas xlrd
  - gem install github-pages html-proofer

script:
  - (cd data && make)
  - jekyll build
  - htmlproof
  - html5validator

branches:
  only:
    - gh-pages
